### ISSUE TITLE
SecureOS refuses to work with pastebin

### ISSUE THREAD

**Issue by tndmadman** [Shuudoushi/OpenOS_Plus#60]
Hello i have the latest opensecurity mod, recently been trying to get it to work but with no success. 
With a network card installed ect i install it with the givin disk then reboot. Tried using pastebin and it said the file was missing, same with wget. The OS also throws loads of error when loading, i managed to get one with a screen shot. http://imgur.com/a/iBQms
.Network card
.APU t2
4x3.5 memory
t3 hdd

**Comment by tndmadman** [comment]
nothing?

**Comment by payonel** [comment]
@tndmadman you probably can offer more patience than ~20 hours for a new ticket for a free service such as a minecraft mod.

At any rate, I looked into the issue and
1. the "crash" you see is somewhat benign - it appears that secureos is trying to autorun scripts for users, but there may not be a $USER env var which causes that script to fail. There doesn't appear to be any negative side affects.
2. wget and pastebin used to be provided "magically" when you add an internet card in your oc computer. That is no longer the case, those two programs have been added to core OpenOS -- and SecureOS would need to copy these two programs to their /bin as well.

**Comment by payonel** [comment]
In the meantime, you can create the files yourself in-game
1. copy all the text from: https://raw.githubusercontent.com/MightyPirates/OpenComputers/master-MC1.7.10/src/main/resources/assets/opencomputers/loot/openos/bin/wget.lua
2. `edit /bin/wget.lua`
3. press INSERT to paste the text
4. save and close the file

Repeat steps 1-4 but for https://raw.githubusercontent.com/MightyPirates/OpenComputers/master-MC1.7.10/src/main/resources/assets/opencomputers/loot/openos/bin/pastebin.lua and `/bin/pastebiin.lua`

**Comment by MJRLegends** [comment]
@payonel Thanks for your reply to @tndmadman issues. 

Hes a player on my server and of my pack "Space Astronomy" (which im the owner/developer of both) and i was informed of this issue a few hours ago that he has posted to you (when he posted above referenced issue for me at request by me)

Is there anything that could easily be done to stop the below issue, i understand there is no errors or issues being caused by this but it would be nice for it to not show a error which then players think something is broken...
`the "crash" you see is somewhat benign - it appears that secureos is trying to autorun scripts for users, but there may not be a $USER env var which causes that script to fail. There doesn't appear to be any negative side affects.`

**Comment by payonel** [comment]
You'd have to edit the /.autorun.lua
I've proposed a PR for that: https://github.com/Shuudoushi/SecureOS/pull/61

**Comment by tndmadman** [comment]
thanks for the info, ill give it a try when i get back into town

**Comment by Shuudoushi** [comment]
Yeah... I've been busy as all hell for quite some time now, here in the next few days I'll see what I can do about bringing SOS up to par with OpenOS. But I can't promise any miracles as all changes to OpenOS must be merged to SOS by hand x.x

**Comment by MJRLegends** [comment]
Sounds good

**Comment by Shuudoushi** [comment]
Been so long since I've used github that I forgot I can close issues through commits... Either way, payonel's changes have been merged and I've updated the required version numbers to allow using the update script to fix any computers SOS is installed on.
