### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by Paradoxica6** [Shuudoushi/OpenOS_Plus#74]
This is an issue many people have been having when trying to install Secure OS. I Tried install method 2 and 3 since the floppy disk with Secure OS is nowhere to be found. Here is the error:
![untitled](https://user-images.githubusercontent.com/33349742/50523722-59f6b700-0ada-11e9-8334-8597f2180a47.png)

**Comment by CaitlynMainer** [comment]
If the floppy you're referring to is supposed to come from OpenSecurity it was removed because of this exact issue.  Shuudoushi hasn't been online in about 2 years, I know @payonel was at one point working on updating this for newer OpenComputers support but I don't know how far that got.  But basically don't expect much in the way of support for this anymore.

**Comment by george2781** [comment]
RIP SecureOS, (No seriously I actually really liked this thing, too bad it's not supported in 1.12.2)
